
target 'Tests-iOS' do

	platform :ios, '8.0'
	use_frameworks!

	pod 'StringUtilities', :path => '../'
	pod 'Nimble', '~> 7.0.0'

end

target 'Tests-macOS' do

	platform :osx, '10.10'
	use_frameworks!

	pod 'StringUtilities', :path => '../'
	pod 'Nimble', '~> 7.0.0'

end
