---
format_version: 1.2.0
default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git
trigger_map:
- push_branch: "*"
  workflow: primary
- pull_request_source_branch: "*"
  workflow: primary
workflows:
  primary:
    steps:
    - activate-ssh-key@3.1.1:
        run_if: '{{getenv "SSH_RSA_PRIVATE_KEY" | ne ""}}'
    - git-clone@3.3.4: {}
    - certificate-and-profile-installer@1.7.0: {}
    - cocoapods-install@1.5.7: {}
    - xcode-test:
        inputs:
        - generate_code_coverage_files: 'yes'
        - should_build_before_test: 'no'
    - deploy-to-bitrise-io: {}
app:
  envs:
  - opts:
      is_expand: false
    BITRISE_PROJECT_PATH: Example/Example.xcworkspace
  - opts:
      is_expand: false
    BITRISE_SCHEME_IOS: StringUtilities-iOS
    BITRISE_SCHEME_MACOS: StringUtilities-iOS
