# Based on: http://www.enekoalonso.com/articles/creating-swift-frameworks-for-ios-osx-and-tvos
language: objective-c

os:
  - osx
osx_image: xcode8.3

env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - WORKSPACE=Example.xcworkspace
  - IOS_SCHEME="Tests-iOS"
  - IOS_SDK=iphonesimulator
  - OSX_SCHEME="Tests-macOS"
  - OSX_SDK=macosx
  matrix:
    - DESTINATION="platform=iOS Simulator,name=iPhone 5"    SCHEME="$IOS_SCHEME"    SDK="$IOS_SDK"    POD_LINT="NO"
    - DESTINATION="platform=iOS Simulator,name=iPad Air 2"  SCHEME="$IOS_SCHEME"    SDK="$IOS_SDK"    POD_LINT="NO"
    - DESTINATION="platform=iOS Simulator,name=iPhone 6S"   SCHEME="$IOS_SCHEME"    SDK="$IOS_SDK"    POD_LINT="NO"
    - DESTINATION="arch=x86_64"                             SCHEME="$OSX_SCHEME"    SDK="$OSX_SDK"    POD_LINT="YES"

before_install:
  - bundle install
  - bundle exec pod repo update > /dev/null

install:
  - cd Example
  - bundle exec pod install

before_script:
  - bundle exec pod --version
  - xcodebuild -version
  - xcodebuild -showsdks
  - xcodebuild -workspace "$WORKSPACE" -list

script:

  # Build Framework in Debug and Run Tests
  - set -o pipefail && xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO test | tee xcodebuild.log | bundle exec xcpretty -c -f `xcpretty-travis-formatter`;

  # Run `pod lib lint` if specified
  - if [ $POD_LINT == "YES" ]; then
      cd ../
      bundle exec pod lib lint --verbose;
    fi

after_success:
  - bash <(curl -s https://codecov.io/bash)
